// <auto-generated />
using Lab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab.Migrations
{
    [DbContext(typeof(CotizacionesContext))]
    partial class CotizacionesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Lab.Models.Cotizacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Estado");

                    b.Property<string>("Monto");

                    b.Property<string>("NombreCliente");

                    b.Property<string>("RUT");

                    b.Property<DateTime>("fechaCreacion");

                    b.Property<DateTime>("fechaRevision");

                    b.HasKey("ID");

                    b.HasIndex("RUT");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("Lab.Models.Persona", b =>
                {
                    b.Property<string>("Rut")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Materno");

                    b.Property<string>("Nombre");

                    b.Property<string>("Paterno");

                    b.HasKey("Rut")
                        .HasName("PK_Personas");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Lab.Models.Cotizacion", b =>
                {
                    b.HasOne("Lab.Models.Persona", "persona")
                        .WithMany("listCotizaciones")
                        .HasForeignKey("RUT");
                });
#pragma warning restore 612, 618
        }
    }
}
